### ISSUE TITLE
Breaks GAE Cron

### ISSUE THREAD

**Issue by Splaktar** [JustinBeckwith/yes-https#1]
Ever since we deployed with this, all of our Cron jobs have been failing because they are getting `301` status back.

Just like the health check hack, I think that we need a hack for allowing HTTP requests that have the `X-Appengine-Cron: true` header.

**Comment by JustinBeckwith** [comment]
This is fixed by 38f1f79b555bce9b74c93ff85fb2569ee5fb88d0 - I'm just giving you an additional filter method where you can opt out of specific requests.  Check out:

https://github.com/JustinBeckwith/yes-https#ignoring-specific-requests

Hope this helps!

**Comment by Splaktar** [comment]
@JustinBeckwith I would expect more details from the new docs. Especially a listing of important exceptions and code snippet for App Engine specifically. Otherwise people who try this library are going to run into the health check and cron issues repeatedly. That doesn't make for a good DX.
